package config;

public enum Sprite {

    PLAYER_UP_STOP("sprite/player/player_up_stop.png"),
    PLAYER_UP_MOVE_RIGHT("sprite/player/player_up_move_right.png"),
    PLAYER_UP_MOVE_LEFT("sprite/player/player_up_move_left.png"),
    PLAYER_DOWN_STOP("sprite/player/player_down_stop.png"),
    PLAYER_DOWN_MOVE_RIGHT("sprite/player/player_down_move_right.png"),
    PLAYER_DOWN_MOVE_LEFT("sprite/player/player_down_move_left.png"),
    PLAYER_RIGHT_STOP("sprite/player/player_right_stop.png"),
    PLAYER_RIGHT_MOVE_RIGHT("sprite/player/player_right_move_right.png"),
    PLAYER_RIGHT_MOVE_LEFT("sprite/player/player_right_move_left.png"),
    PLAYER_LEFT_STOP("sprite/player/player_left_stop.png"),
    PLAYER_LEFT_MOVE_RIGHT("sprite/player/player_left_move_right.png"),
    PLAYER_LEFT_MOVE_LEFT("sprite/player/player_left_move_left.png"),
    PLAYER2_UP_STOP("sprite/player/player2_up_stop.png"),
    PLAYER2_UP_MOVE_RIGHT("sprite/player/player2_up_move_right.png"),
    PLAYER2_UP_MOVE_LEFT("sprite/player/player2_up_move_left.png"),
    PLAYER2_DOWN_STOP("sprite/player/player2_down_stop.png"),
    PLAYER2_DOWN_MOVE_RIGHT("sprite/player/player2_down_move_right.png"),
    PLAYER2_DOWN_MOVE_LEFT("sprite/player/player2_down_move_left.png"),
    PLAYER2_RIGHT_STOP("sprite/player/player2_right_stop.png"),
    PLAYER2_RIGHT_MOVE_RIGHT("sprite/player/player2_right_move_right.png"),
    PLAYER2_RIGHT_MOVE_LEFT("sprite/player/player2_right_move_left.png"),
    PLAYER2_LEFT_STOP("sprite/player/player2_left_stop.png"),
    PLAYER2_LEFT_MOVE_RIGHT("sprite/player/player2_left_move_right.png"),
    PLAYER2_LEFT_MOVE_LEFT("sprite/player/player2_left_move_left.png"),
    PLAYER3_UP_STOP("sprite/player/player3_up_stop.png"),
    PLAYER3_UP_MOVE_RIGHT("sprite/player/player3_up_move_right.png"),
    PLAYER3_UP_MOVE_LEFT("sprite/player/player3_up_move_left.png"),
    PLAYER3_DOWN_STOP("sprite/player/player3_down_stop.png"),
    PLAYER3_DOWN_MOVE_RIGHT("sprite/player/player3_down_move_right.png"),
    PLAYER3_DOWN_MOVE_LEFT("sprite/player/player3_down_move_left.png"),
    PLAYER3_RIGHT_STOP("sprite/player/player3_right_stop.png"),
    PLAYER3_RIGHT_MOVE_RIGHT("sprite/player/player3_right_move_right.png"),
    PLAYER3_RIGHT_MOVE_LEFT("sprite/player/player3_right_move_left.png"),
    PLAYER3_LEFT_STOP("sprite/player/player3_left_stop.png"),
    PLAYER3_LEFT_MOVE_RIGHT("sprite/player/player3_left_move_right.png"),
    PLAYER3_LEFT_MOVE_LEFT("sprite/player/player3_left_move_left.png"),

    PNJ1_UP("sprite/pnj/pnj1_up.png"),
    PNJ1_DOWN("sprite/pnj/pnj1_down.png"),
    PNJ1_RIGHT("sprite/pnj/pnj1_right.png"),
    PNJ1_LEFT("sprite/pnj/pnj1_left.png"),
    PNJ2_UP("sprite/pnj/pnj2_up.png"),
    PNJ2_DOWN("sprite/pnj/pnj2_down.png"),
    PNJ2_RIGHT("sprite/pnj/pnj2_right.png"),
    PNJ2_LEFT("sprite/pnj/pnj2_left.png"),
    PNJ3_UP("sprite/pnj/pnj3_up.png"),
    PNJ3_DOWN("sprite/pnj/pnj3_down.png"),
    PNJ3_RIGHT("sprite/pnj/pnj3_right.png"),
    PNJ3_LEFT("sprite/pnj/pnj3_left.png"),
    PNJ4_UP("sprite/pnj/pnj4_up.png"),
    PNJ4_DOWN("sprite/pnj/pnj4_down.png"),
    PNJ4_RIGHT("sprite/pnj/pnj4_right.png"),
    PNJ4_LEFT("sprite/pnj/pnj4_left.png"),
    PNJ5_UP("sprite/pnj/pnj5_up.png"),
    PNJ5_DOWN("sprite/pnj/pnj5_down.png"),
    PNJ5_RIGHT("sprite/pnj/pnj5_right.png"),
    PNJ5_LEFT("sprite/pnj/pnj5_left.png"),
    PNJ6_UP("sprite/pnj/pnj6_up.png"),
    PNJ6_DOWN("sprite/pnj/pnj6_down.png"),
    PNJ6_RIGHT("sprite/pnj/pnj6_right.png"),
    PNJ6_LEFT("sprite/pnj/pnj6_left.png"),
    PNJ7_UP("sprite/pnj/pnj7_up.png"),
    PNJ7_DOWN("sprite/pnj/pnj7_down.png"),
    PNJ7_RIGHT("sprite/pnj/pnj7_right.png"),
    PNJ7_LEFT("sprite/pnj/pnj7_left.png"),

    WHITE_CAT_UP("sprite/animal/white_cat_up.png"),
    WHITE_CAT_DOWN("sprite/animal/white_cat_down.png"),
    WHITE_CAT_RIGHT("sprite/animal/white_cat_right.png"),
    WHITE_CAT_LEFT("sprite/animal/white_cat_left.png"),
    GREY_CAT_UP("sprite/animal/grey_cat_up.png"),
    GREY_CAT_DOWN("sprite/animal/grey_cat_down.png"),
    GREY_CAT_RIGHT("sprite/animal/grey_cat_right.png"),
    GREY_CAT_LEFT("sprite/animal/grey_cat_left.png"),
    BLACK_CAT_UP("sprite/animal/black_cat_up.png"),
    BLACK_CAT_DOWN("sprite/animal/black_cat_down.png"),
    BLACK_CAT_RIGHT("sprite/animal/black_cat_right.png"),
    BLACK_CAT_LEFT("sprite/animal/black_cat_left.png"),
    SNAKE_UP("sprite/animal/snake_up.png"),
    SNAKE_DOWN("sprite/animal/snake_down.png"),
    SNAKE_RIGHT("sprite/animal/snake_right.png"),
    SNAKE_LEFT("sprite/animal/snake_left.png"),
    FOX_UP("sprite/animal/fox_up.png"),
    FOX_DOWN("sprite/animal/fox_down.png"),
    FOX_RIGHT("sprite/animal/fox_right.png"),
    FOX_LEFT("sprite/animal/fox_left.png"),

    ROCKET_UP("sprite/rocket/rocket_up.png"),
    ROCKET_DOWN("sprite/rocket/rocket_down.png"),

    SPACESHIP_1("sprite/rocket/spaceship_1.png"),
    SPACESHIP_2("sprite/rocket/spaceship_2.png"),
    SPACESHIP_3("sprite/rocket/spaceship_3.png"),
    SPACESHIP_4("sprite/rocket/spaceship_4.png"),
    SPACESHIP_5("sprite/rocket/spaceship_5.png"),
    SPACESHIP_6("sprite/rocket/spaceship_6.png"),
    SPACESHIP_7("sprite/rocket/spaceship_7.png"),
    SPACESHIP_8("sprite/rocket/spaceship_8.png"),
    SPACESHIP_9("sprite/rocket/spaceship_9.png"),
    SPACESHIP_10("sprite/rocket/spaceship_10.png"),

    CHEST_HIDDEN("sprite/chest/chest_hidden.png"),
    CHEST_CLOSED("sprite/chest/chest_closed.png"),
    CHEST_OPENED("sprite/chest/chest_opened.png"),

    GRASS("sprite/env/grass.png"),
    BUSH("sprite/env/bush.png"),
    HERB("sprite/env/herb.png"),
    ROCK("sprite/env/rock.png"),
    BRIDGE("sprite/env/bridge.png"),
    FOG("sprite/env/fog.png"),
    SAND("sprite/env/sand.png"),
    ROAD("sprite/env/road.png"),
    ROAD_UP_DOWN("sprite/env/road_up_down.png"),
    ROAD_UP_RIGHT("sprite/env/road_up_right.png"),
    ROAD_LEFT_RIGHT("sprite/env/road_left_right.png"),

    FLOOR("sprite/env/floor.png"),
    FLOOR_UP("sprite/env/floor_up.png"),
    FLOOR_UP_LEFT("sprite/env/floor_up_left.png"),
    FLOOR_UP_RIGHT("sprite/env/floor_up_right.png"),
    FLOOR_DOWN("sprite/env/floor_down.png"),
    FLOOR_DOWN_LEFT("sprite/env/floor_down_left.png"),
    FLOOR_DOWN_RIGHT("sprite/env/floor_down_right.png"),
    FLOOR_LEFT("sprite/env/floor_left.png"),
    FLOOR_RIGHT("sprite/env/floor_right.png"),

    TREE("sprite/tree/tree.png"),
    TREE_UP("sprite/tree/tree_up.png"),
    TREE_UP_LEFT("sprite/tree/tree_up_left.png"),
    TREE_UP_LEFT_RIGHT("sprite/tree/tree_up_left_right.png"),
    TREE_UP_RIGHT("sprite/tree/tree_up_right.png"),
    TREE_UP_DOWN("sprite/tree/tree_up_down.png"),
    TREE_DOWN("sprite/tree/tree_down.png"),
    TREE_DOWN_LEFT("sprite/tree/tree_down_left.png"),
    TREE_DOWN_LEFT_RIGHT("sprite/tree/tree_down_left_right.png"),
    TREE_DOWN_RIGHT("sprite/tree/tree_down_right.png"),
    TREE_LEFT("sprite/tree/tree_left.png"),
    TREE_LEFT_RIGHT("sprite/tree/tree_left_right.png"),
    TREE_LEFT_UP_DOWN("sprite/tree/tree_left_up_down.png"),
    TREE_RIGHT("sprite/tree/tree_right.png"),
    TREE_RIGHT_UP_DOWN("sprite/tree/tree_right_up_down.png"),
    TREE2("sprite/tree/tree2.png"),
    TREE2_UP("sprite/tree/tree2_up.png"),
    TREE2_UP_LEFT("sprite/tree/tree2_up_left.png"),
    TREE2_UP_LEFT_RIGHT("sprite/tree/tree2_up_left_right.png"),
    TREE2_UP_RIGHT("sprite/tree/tree2_up_right.png"),
    TREE2_UP_DOWN("sprite/tree/tree2_up_down.png"),
    TREE2_DOWN("sprite/tree/tree2_down.png"),
    TREE2_DOWN_LEFT("sprite/tree/tree2_down_left.png"),
    TREE2_DOWN_LEFT_RIGHT("sprite/tree/tree2_down_left_right.png"),
    TREE2_DOWN_RIGHT("sprite/tree/tree2_down_right.png"),
    TREE2_LEFT("sprite/tree/tree2_left.png"),
    TREE2_LEFT_RIGHT("sprite/tree/tree2_left_right.png"),
    TREE2_LEFT_UP_DOWN("sprite/tree/tree2_left_up_down.png"),
    TREE2_RIGHT("sprite/tree/tree2_right.png"),
    TREE2_RIGHT_UP_DOWN("sprite/tree/tree2_right_up_down.png"),

    WATER("sprite/water/water.png"),
    WATER_UP("sprite/water/water_up.png"),
    WATER_UP_LEFT("sprite/water/water_up_left.png"),
    WATER_UP_LEFT_RIGHT("sprite/water/water_up_left_right.png"),
    WATER_UP_RIGHT("sprite/water/water_up_right.png"),
    WATER_UP_DOWN("sprite/water/water_up_down.png"),
    WATER_DOWN("sprite/water/water_down.png"),
    WATER_DOWN_LEFT("sprite/water/water_down_left.png"),
    WATER_DOWN_LEFT_RIGHT("sprite/water/water_down_left_right.png"),
    WATER_DOWN_RIGHT("sprite/water/water_down_right.png"),
    WATER_LEFT("sprite/water/water_left.png"),
    WATER_LEFT_RIGHT("sprite/water/water_left_right.png"),
    WATER_LEFT_UP_DOWN("sprite/water/water_left_up_down.png"),
    WATER_RIGHT("sprite/water/water_right.png"),
    WATER_RIGHT_UP_DOWN("sprite/water/water_right_up_down.png"),

    HOUSE1_1("sprite/house/house1_1.png"),
    HOUSE1_2("sprite/house/house1_2.png"),
    HOUSE1_3("sprite/house/house1_3.png"),
    HOUSE1_4("sprite/house/house1_4.png"),
    HOUSE2_1("sprite/house/house2_1.png"),
    HOUSE2_2("sprite/house/house2_2.png"),
    HOUSE2_3("sprite/house/house2_3.png"),
    HOUSE2_4("sprite/house/house2_4.png"),

    CINEMATIC("sprite/cinematic/eevolution1.jpg"),
    CINEMATIC2("sprite/cinematic/eevolution2.jpg"),
    CINEMATIC3("sprite/cinematic/eevolution3.jpg"),

    LOAD("sprite/app/load.jpg"),
    BACKGROUND_LAUNCHER("sprite/app/background_launcher.jpg"),
    BACKGROUND_OPTIONS("sprite/app/background_options.jpg"),
    BACKGROUND_CREDITS("sprite/app/background_credits.jpg"),
    ;

    private String spritePath;

    Sprite(String spritePath) {
        this.spritePath = spritePath;
    }

    public String getSpritePath() {
        return this.spritePath;
    }
}
